---
output: pdf_document
header-includes: 
- \usepackage[utf8]{inputenc}
- \usepackage[T1]{fontenc}
- \usepackage[ngerman]{babel}
- \usepackage{amsmath,amssymb,amsthm}
- \usepackage{dsfont}
- \usepackage{listings}
- \usepackage{floatrow}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- '\fancyhead[C,C]{Gruppe: Robin Baudisch, Merlin Kopfmann, Maximilian Neudert}'
- \fancyhead[L]{}
- \fancyhead[R]{}
- \fancyfoot[C,C]{\thepage}
- \renewcommand{\footrulewidth}{0.4pt}
---

<style type="text/css">
body{
  font-size: 12px;
}
h1 {
  font-size: 18px;
}
h1 {
  font-size: 14px;
}
h1 {
  font-size: 12px;
}
</style>

```{r global_options, include=FALSE}
knitr::opts_chunk$set(error=TRUE,        # Keep compiling upon error
                      collapse=TRUE,     # collapse by default
                      echo=TRUE,         # echo code by default
                      comment = "#>",    # change comment character
                      fig.width = 10,     # set figure width
                      out.width = "100%", # set width of displayed images
                      warning=TRUE,      # show R warnings
                      message=FALSE)     # show R messages
```

<!---** Hochschule Darmstadt | Studiengang Data Science | Sommersemester 2019 **--->

set.seed(42)

# Arbeitsblatt 5

## Aufgabe 1

### a)

```{r}
# daten vorbereiten
load('awards.Rdata')
data = awards
data$prog_num = as.numeric(as.factor(awards$prog))

# poisson regression
plm = glm(num_awards~math+prog_num, data = data, family= poisson)
plm
```

Wir sehen, dass der Ausbildungstyp einen stärkeren Einfluss auf die Anzahl an Awards hat als die letzte Mathenote.

### b)

```{r}
library(ggplot2)
library(tidyr)

newdf = data.frame(math = data$math, prog_num = data$prog_num)
pred = predict.glm(plm, newdf, type='response')
plotdf = data.frame(prog = data$prog, math = data$math, exp_awards = pred)

gg = ggplot(
  data = plotdf,
  mapping = aes(
    x = math,
    y = exp_awards,
    color = prog
  )
) + geom_smooth(
  method = "glm",
  se = FALSE
)
gg

```










